/**
 * PLACES-001 — repository layer for the place tables (`places`,
 * `place_candidates`, `place_passages`; PRODUCT_EXPERIENCE_PLAN §C.1). Called
 * from `scripts/sync-places.mts` (standalone CLI, via `tsx`), so — like
 * `lib/db/graphEdges.ts` — it does NOT import "server-only" or the app's `db`
 * singleton: every function takes its `Database` as an explicit parameter.
 *
 * Rows come from `content/places/places.jsonl` (generated by
 * `tools/build-places.mjs` from the OpenBible.info Bible Geocoding Data,
 * CC BY 4.0) after `scripts/content/placeSchema.ts` has validated them and
 * resolved every passage against the real canon. This module is transport, not
 * authorship: it writes exactly what it is handed.
 */

import { inArray, sql } from "drizzle-orm";

import { placeCandidates, placePassages, places } from "@/db/schema";
import type { PlaceKind, PlaceTier } from "@/db/schema";
import type { Database } from "@/lib/db";
import { diffAbsentIds } from "@/lib/db/graphEdges";
import type { CanonicalRangeV1 } from "@/lib/contracts/range-v1";

/** One place, as `db:sync-places` writes it (structurally `CompiledPlace` from `scripts/content/placeSchema.ts`). */
export interface PlaceSyncRow {
  id: string;
  name: string;
  ancientId: string;
  kind: PlaceKind;
  tier: PlaceTier;
  lon: number | null;
  lat: number | null;
  coordinateBasis: string | null;
  modernName: string | null;
  note: string | null;
  sourceId: string;
  datasetScore: number;
  voteCount: number;
  identificationsInDataset: number;
  candidates: { description: string; lon: number; lat: number; score: number }[];
  passages: { range: CanonicalRangeV1; inDatasetVerseList: boolean; note: string | null }[];
}

/** One statement of a `db.batch` call. */
type BatchStatement = Parameters<Database["batch"]>[0][number];

/** Places per atomic batch. Each batch is one Postgres transaction (Neon HTTP `db.batch`). */
export const PLACE_CHUNK_SIZE = 50;
/** Rows per single INSERT statement: 1,000 rows x 6 columns is far under the 65,535-parameter limit. */
export const PLACE_INSERT_ROWS = 1000;

/**
 * Upserts places keyed on `places.id` and REPLACES each place's candidate and
 * passage sets. Idempotent: an unchanged file re-syncs to the same rows; a
 * corrected tier / note / coordinate / passage list is picked up in place, and
 * a candidate or passage removed from the file is removed from the database
 * (delete-then-insert of that place's children). Each chunk of places is ONE
 * `db.batch` (a single transaction on the Neon HTTP driver), so a place never
 * ends up with its old row and a new half-set of children.
 *
 * `excluded.*` (not JS-side values) in `set`, so a multi-row INSERT applies each
 * conflicting row's OWN incoming values. `created_at` and `release_id` are left
 * out of `set` (an existing row keeps them). Places that disappear from the
 * file are NOT deleted: removal is a deliberate, reviewed act, not a side
 * effect of a sync.
 */
export async function upsertPlaceRows(
  db: Database,
  rows: readonly PlaceSyncRow[],
  chunkSize: number = PLACE_CHUNK_SIZE,
): Promise<void> {
  for (let start = 0; start < rows.length; start += chunkSize) {
    const chunk = rows.slice(start, start + chunkSize);
    if (chunk.length === 0) continue;
    const ids = chunk.map((row) => row.id);

    const candidateRows = chunk.flatMap((row) =>
      row.candidates.map((candidate, ordinal) => ({
        placeId: row.id,
        ordinal,
        description: candidate.description,
        lon: candidate.lon,
        lat: candidate.lat,
        score: candidate.score,
      })),
    );
    const passageRows = chunk.flatMap((row) =>
      row.passages.map((passage, ordinal) => ({
        placeId: row.id,
        ordinal,
        range: passage.range,
        inDatasetVerseList: passage.inDatasetVerseList,
        note: passage.note,
      })),
    );

    const statements: BatchStatement[] = [
      db
        .insert(places)
        .values(
          chunk.map((row) => ({
            id: row.id,
            name: row.name,
            ancientId: row.ancientId,
            kind: row.kind,
            tier: row.tier,
            lon: row.lon,
            lat: row.lat,
            coordinateBasis: row.coordinateBasis,
            modernName: row.modernName,
            note: row.note,
            sourceId: row.sourceId,
            datasetScore: row.datasetScore,
            voteCount: row.voteCount,
            identificationsInDataset: row.identificationsInDataset,
          })),
        )
        .onConflictDoUpdate({
          target: places.id,
          set: {
            name: sql`excluded.name`,
            ancientId: sql`excluded.ancient_id`,
            kind: sql`excluded.kind`,
            tier: sql`excluded.tier`,
            lon: sql`excluded.lon`,
            lat: sql`excluded.lat`,
            coordinateBasis: sql`excluded.coordinate_basis`,
            modernName: sql`excluded.modern_name`,
            note: sql`excluded.note`,
            sourceId: sql`excluded.source_id`,
            datasetScore: sql`excluded.dataset_score`,
            voteCount: sql`excluded.vote_count`,
            identificationsInDataset: sql`excluded.identifications_in_dataset`,
          },
        }),
      db.delete(placeCandidates).where(inArray(placeCandidates.placeId, ids)),
    ];
    for (let s = 0; s < candidateRows.length; s += PLACE_INSERT_ROWS) {
      statements.push(db.insert(placeCandidates).values(candidateRows.slice(s, s + PLACE_INSERT_ROWS)));
    }
    statements.push(db.delete(placePassages).where(inArray(placePassages.placeId, ids)));
    for (let s = 0; s < passageRows.length; s += PLACE_INSERT_ROWS) {
      statements.push(db.insert(placePassages).values(passageRows.slice(s, s + PLACE_INSERT_ROWS)));
    }

    await db.batch(statements as [BatchStatement, ...BatchStatement[]]);
  }
}

/**
 * Which of `ids` have NO row in `places`. Deduped and sorted (via
 * `diffAbsentIds`). The release-side check for a lesson's `placeIds[]`, the
 * sibling of `findMissingConnectionIds` / `findMissingSourceIds`. Throws --
 * never returns "nothing missing" -- if the query fails (e.g. migration 0014
 * not yet applied).
 */
export async function findMissingPlaceIds(db: Database, ids: readonly string[]): Promise<string[]> {
  const unique = [...new Set(ids)];
  if (unique.length === 0) return [];
  const rows = await db.select({ id: places.id }).from(places).where(inArray(places.id, unique));
  return diffAbsentIds(unique, rows.map((row) => row.id));
}
