#!/usr/bin/env -S npx tsx
/**
 * PLACES-001 — syncs `content/places/places.jsonl` (the place layer, plan
 * §C.1) into the real curated `places` / `place_candidates` / `place_passages`
 * Postgres tables. The place-side sibling of `scripts/sync-connections.mts`
 * (CURATEDEDGES-002) and `scripts/sync-source-registry.mts` (SOURCESYNC-001),
 * built the same way.
 *
 * DATA PROVENANCE: `content/places/places.jsonl` is GENERATED by
 * `tools/build-places.mjs` from the OpenBible.info Bible Geocoding Data
 * (CC BY 4.0, dataset commit pinned in `content/places/DATASET.json`), with
 * hand-maintained tier/note overrides in `content/places/curation.json`.
 * Coordinates are copied from the dataset by that script, never typed. This
 * script never invents or infers any of it: it validates the whole directory
 * with the SAME validation `content:validate` runs (`scripts/content/placeSchema.ts`
 * via `loadPlaces`: unlocated => no coordinates, disputed/uncertain => note or
 * candidates, every passage in bounds of the real BSB canon, duplicate ids,
 * attribution present, curation and generated rows agree) and copies the rows
 * into Postgres exactly as written. It refuses to write anything if ANY row is
 * invalid -- never a partial sync.
 *
 * ORDER: run `npm run db:sync-sources` first. `places.source_id` is a real FK
 * to `sources.id` (the entry `source-openbible-geocoding` in
 * `content/source-registry.json`); this script checks up front that the row
 * exists and refuses with a clear message instead of a raw FK violation.
 *
 * MIGRATION: requires migration 0014 (`places`, `place_candidates`,
 * `place_passages`, enums `place_kind` / `place_tier`) applied first.
 *
 * IDEMPOTENT: keyed on `places.id`; each place's candidate and passage sets are
 * replaced atomically (one `db.batch` per chunk of places). An unchanged file
 * re-syncs to the same rows. Places removed from the file are NOT deleted.
 * See `lib/db/places.ts`'s `upsertPlaceRows`.
 *
 * ATTRIBUTION: the data is CC BY 4.0. The exact string
 * "Place data © OpenBible.info, CC BY 4.0" (`DATASET.json`) must be shown
 * wherever places are shown.
 *
 * HUMAN GATE (matching `scripts/sync-source-registry.mts` /
 * `scripts/sync-connections.mts` / `scripts/import-cross-references.mts`): this
 * script is NOT run against any real `DATABASE_URL` as part of building it --
 * that is Ken's own decision to trigger, or a follow-up task with real output
 * pasted. This repo has exactly one Postgres instance (production; see
 * `.env.production.local`) -- there is no separate dev/test database to
 * rehearse against, so a live run here would write directly to production data.
 *
 * Run via:
 *
 *   npm run db:sync-places
 *
 * (requires `DATABASE_URL` in the environment or `web/.env.local`, the same
 * convention `db:seed` / `db:sync-sources` already use).
 *
 * Author: Kenneth Hill
 */

import path from "node:path";
import { fileURLToPath } from "node:url";

import { drizzle } from "drizzle-orm/neon-http";

import * as schema from "@/db/schema";
import { findMissingSourceIds } from "@/lib/db/graphEdges";
import { upsertPlaceRows } from "@/lib/db/places";

import { loadPlaces, loadSourceRegistryIds, PLACES_DIR } from "./content/validate";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
// web/scripts -> web -> repo root -> content/source-registry.json.
const REGISTRY_FILE = path.join(SCRIPT_DIR, "..", "..", "content", "source-registry.json");

async function main(): Promise<void> {
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is required (set it in the environment or web/.env.local)");
  }

  console.log(`Reading ${path.relative(process.cwd(), PLACES_DIR)} ...`);
  const loaded = loadPlaces(PLACES_DIR, loadSourceRegistryIds(REGISTRY_FILE));
  if (!loaded.ok) {
    console.error(`db:sync-places refused -- ${loaded.errors.length} problem(s), nothing written:`);
    for (const error of loaded.errors) console.error(`  - ${error}`);
    process.exitCode = 1;
    return;
  }
  const rows = loaded.places;
  console.log(`Found ${rows.length} place${rows.length === 1 ? "" : "s"}.`);
  if (rows.length === 0) {
    console.log("Nothing to sync.");
    return;
  }

  const db = drizzle(process.env.DATABASE_URL, { schema });

  const missingSources = await findMissingSourceIds(db, rows.map((row) => row.sourceId));
  if (missingSources.length > 0) {
    throw new Error(
      `db:sync-places refused: sourceIds have no row in the real Postgres sources table ` +
        `(run "npm run db:sync-sources" first): ${missingSources.join(", ")}`,
    );
  }

  await upsertPlaceRows(db, rows);

  const candidates = rows.reduce((sum, row) => sum + row.candidates.length, 0);
  const passages = rows.reduce((sum, row) => sum + row.passages.length, 0);
  console.log("");
  console.log(
    `Synced ${rows.length} place(s), ${candidates} candidate(s), ${passages} passage(s) into "places" / ` +
      '"place_candidates" / "place_passages", keyed on place id -- a corrected file updates its rows in place; ' +
      "an unchanged one is a no-op. Places removed from the file are not deleted.",
  );
}

main().catch((error: unknown) => {
  console.error("[fatal] Unhandled error in sync-places:", error);
  process.exitCode = 1;
});
